### ISSUE TITLE
Add Simple Achievements for Player Guide

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#112]
- ~~Better Questing: http://www.curse.com/mc-mods/minecraft/238856-better-questing~~
  - ~~Better Questing Standard Expansion: http://minecraft.curseforge.com/projects/better-questing-standard-expansion~~
- ~~HQM: http://www.curse.com/mc-mods/minecraft/hardcore-questing-mode~~
  - ~~Lore Expansion: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2091967-lore-expansion-1-7-x~~
- Simple Achievements: http://www.curse.com/mc-mods/minecraft/231126-simple-achievements
- ~~Lore Expansion: http://minecraft.curseforge.com/projects/lore-expansion~~

I need a way to provide guidance for the player through the pack, without providing handouts like the standard set of HQM packs.  If I do add HQM, it'll just be a set of quests, not a series of tasks to get rewards.  Better Questing seems nice, but still looks like it adds QUESTS.  Simple Achievements is basically a checklist from what I can tell, and that might be all I need.  We'll see.

Added Lore Expansion, although I'm not sure how I could give the players pages, since it's intended for adventure maps so they're probably only able to be placed manually.  I'll have to investigate.

EDIT: I decided to go with Simple Achievements, as that way I can make an outline of the different stages of the pack, as well as some checkboxes for whatever needs to be completed to progress between then.

**Comment by UndeadZeratul** [comment]
I think I'm going to go with Simple Achievements, because that way I can make an outline of the different stages, as well as checkboxes for what needs to be done to progress.

**Comment by Nincodedo** [comment]
Just a minor point, I think anything that you'd normally do in vanilla, aka kill the ender dragon, doesn't need to be really added under Simple Achievements.  Plus I think it already has a vanilla achievement.
