### ISSUE TITLE
Primitive Mobs jar is corrupted on Jenkins Server

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#157]
![image](https://cloud.githubusercontent.com/assets/6988914/18575049/dd0f1818-7b98-11e6-94fa-1709a8eb63d3.png)
_The file on the left is from the old Curse image (back on v0.4.0 when it would still download from Curse), and the file on the right is from the FTB Launcher, v1.1.1_

It seems that somewhere between v1.0.0 and v1.1.1 Primitive Mobs somehow got corrupted and thus never loads.

This should really only affect FTB and Technic, as they are the two launchers that rely on the jar files themselves, rather than using the manifest to fetch the files upon installation.

Either way, the modpack downloader cache probably just needs to be cleaned up a bit on our Jenkins server before the next hotfix release, as it looks like the downloader just simply 
[copied the file from cache](https://cloud.githubusercontent.com/assets/6988914/18575101/6a72630e-7b99-11e6-9f4c-74ac0edd223b.png) instead of downloading it.

**Comment by Nincodedo** [comment]
Cache has been cleared for Primitive Mobs.
