### ISSUE TITLE
Punching trees doesn't hurt

### ISSUE THREAD

**Issue by Nincodedo** [UndeadZeratul/ThereWillBeBlood#159]

**Comment by UndeadZeratul** [comment]
According to [this](https://github.com/einsteinsci/betterbeginnings/wiki/Block-Breaking#stuck), it seems that because I'm on peaceful in the earliest stage of my LP, I don't get hurt from this mechanic; marking this "as intended" and closing

**Comment by Roshag** [comment]
Nope, there is a bug with Natura trees. I'm sure of Amaranth wood
