### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Roshag** [UndeadZeratul/ThereWillBeBlood#162]
Did someone mention not disappearing statuses like heatstroke, insomnia and hypothermia? I don't know what mod is it. Another problem - crash when rightclicking some objects like kiln and campfire with torch. #159 with some of Natura trees. Not sure if temperature bar works well - should i get heated when carrying lava bucket?
P.S. Will make log file for torch a bit later
[crash-2017-06-30_17.26.50-server.txt](https://github.com/UndeadZeratul/ThereWillBeBlood/files/1115509/crash-2017-06-30_17.26.50-server.txt)
[crash-2017-06-30_17.26.55-client.txt](https://github.com/UndeadZeratul/ThereWillBeBlood/files/1115510/crash-2017-06-30_17.26.55-client.txt)

**Comment by UndeadZeratul** [comment]
Enviromine is the mod that adds the temperature mechanics and status effects.  It also adds the burning torches, which is what causes the crash whenever you right-click on certain blocks with a torch in hand.

I wasn't aware of the Natura trees specifically, but when I tried punching a BoP tree while in peaceful mode I didn't get hurt.

You have to have items in your hotbar to be affected by them, unless Enviromine updated that limitation in a recent update.

I haven't touched this pack in a while so it's hard to say without looking for some mod updates what has been fixed.
