### ISSUE TITLE
Can't make any tools

### ISSUE THREAD

**Issue by UndeadZeratul** [UndeadZeratul/ThereWillBeBlood#88]
So in re-balancing the metal temperatures, I've come across the realization that it's impossible to progress anywhere past the stone tools stage.  You can mine lead/tin/zinc/aluminum with a stone pick, but melting down those metals requires a smeltery.  That's fine and good, except now how do you get them into ingots?  An ingot cast, which costs Aluminum Brass, which requires copper, which needs a tin/lead pick to break, which can't be crafted because ingots need to be casted.

Until I come up with a better way, I'm going to have to allow tin and/or lead to be melted down in a normal furnace.  That way those first few ores and whatnot can be melted down and workable, so players can actually progress.

**Comment by Nincodedo** [comment]
:clap:

**Comment by UndeadZeratul** [comment]
Actually, I've fixed this in a better way: allow crafting of the FSP clay molds and use those as the early metal casting, rather than aluminum brass.
