### ISSUE TITLE
Unknown Mod

### ISSUE THREAD

**Issue by Myth494** [UndeadZeratul/ThereWillBeBlood#89]
been playing this pack and love it, but i want to know what's causing the total darkness at nights. i cant seem to find it

**Comment by UndeadZeratul** [comment]
There's a few mods that do this, The two that I'm aware of are [Hardcore Darkness](http://curse.com/project/225957), and the one that I use, [Random Things](http://curse.com/project/59816).

The config setting in Random Things is located [here](https://github.com/UndeadZeratul/ThereWillBeBlood/blob/72d7e4dff50382ff8aea7e9abe975d4a4bca9c0b/config/RandomThings.cfg#L142).

**Comment by Myth494** [comment]
oh sweet! haha didnt think it would be in random things! :P

and i cant wait! i dont mind starting again every now and then :P makes it more interesting :P
