### ISSUE TITLE
[0.3.0] Suffocating while Sleep causes lockup

### ISSUE THREAD

**Issue by EchoingZen** [UndeadZeratul/ThereWillBeBlood#92]
If you die by suffocation while attempting to sleep, you will not be able to respawn or quit to title screen.  You will only see the "Leave Bed" option which will do nothing.

To repeat, place a bed in an area that will result in suffocation.  Just wait until your life runs out and you should experience the same thing.  Closing out the modpack will allow you to respawn once you reload the modpack.

**Comment by UndeadZeratul** [comment]
Huh, I'll look into it.  I wonder if it's something in Somnia's code.  Thanks for reporting the bug.

**Comment by UndeadZeratul** [comment]
I was able to recreate in an environment with just somnia and forge.  Seems to be on their end, so I've gone ahead and opened up an issue on their tracker, [here](https://github.com/kingrunes/Somnia/issues/27).  If/when it gets resolved, I'll update the mod and close this issue then.

Thanks again for the report.

**Comment by UndeadZeratul** [comment]
Ah, so I was testing some more and found a bit of a workaround.  If you press escape, it seems to force close the Somnia GUI and allow you to respawn.  I guess that's good enough for now, but I'll still look into updating Somnia if/when it gets updated with a fix.

**Comment by UndeadZeratul** [comment]
Looks like the Somnia dev fixed the issue.  I'll just need to update the mod and hopefully that'll fix this.
